### ISSUE TITLE
Nikola Blog-Template not working in Netlify

### ISSUE THREAD

**Issue by thestrawh8** [getnikola/blog-template#3]
Hi, 
I would like to thanks for creating this blog template to deploy in Netlify. But it suddenly it doesn't seem to work. Build is failing due to some dependency error. Can you kindly help me with this issue.
Thanks in Advance,

![netify](https://user-images.githubusercontent.com/20152870/36683760-6c2f81da-1b44-11e8-8c6a-dedd49e621ad.png)

**Comment by thestrawh8** [comment]
In runtime.txt file 3.6.2 doesn't seem to work like before. It is working only after using 3.6. Iam not completely sure but it is working again after changing it to 3.6. Thanks

**Comment by Kwpolska** [comment]
Fixed that in the template. Thanks for reporting!
